### ISSUE TITLE
unity nav mesh

### ISSUE THREAD

**Issue by rbatistajs** [vincent/recast.js#18]
I have an object that was exported from unity 3d

> g ExportedNavMesh
v 191.12 60.23563 58.68
v 191.2 60.23563 58.76
v 191.2 60.23563 58.2
v 191.12 60.23563 58.68
v 191.2 60.23563 58.2
v 189.4 60.23563 58.2
v 188.72 60.23563 58.68
v 190.64 60.23563 55.68
v 190.72 60.23563 55.76
v 191.2 60.23563 55.27999
v 188.72 60.23563 58.68
v 189.4 60.23563 58.2
v 189.32 60.23563 58.12
v 189 60.23563 57.16
v 188.48 60.23563 58.68
v 188.72 60.23563 58.68
v 189.32 60.23563 58.12
v 189.32 60.23563 57.68
v 189.08 60.23563 57.24
v 191.2 60.23563 56.64
v 191.2 60.23563 55.27999
v 190.72 60.23563 55.76
v 190.72 60.23563 56.2
v 189.4 60.23563 57.6
v 191.2 60.23563 57.6
v 191.2 60.23563 57.24
v 189.08 60.23563 57.24
v 188.48 60.23563 55.27999
v 188.48 60.23563 55.68
v 190.64 60.23563 55.68
v 191.2 60.23563 55.27999
v 189.32 60.23563 57.68
v 189.4 60.23563 57.6
v 189.08 60.23563 57.24
v 188.48 60.23563 56.27999
v 189 60.23563 56.72
v 189.08 60.23563 56.64
v 190.64 60.23563 56.27999
v 188.48 60.23563 56.27999
v 189.08 60.23563 56.64
v 191.2 60.23563 56.64
v 188.48 60.23563 56.27999
v 188.48 60.23563 58.68
v 189 60.23563 57.16
v 189 60.23563 56.72
v 190.72 60.23563 56.2
v 190.64 60.23563 56.27999
v 191.2 60.23563 56.64
v 188.64 60.23563 58.76
v 188.72 60.23563 58.68
v 188.48 60.23563 58.68
v 188.64 60.23563 59.2
v 188.64 60.23563 58.76
v 188.48 60.23563 58.68
v 188.48 60.23563 60.96
v 191.2 60.23563 60.96
v 191.2 60.23563 59.2
v 191.12 60.23563 59.27999
v 191.2 60.23563 60.96
v 191.12 60.23563 59.27999
v 188.72 60.23563 59.27999
v 188.48 60.23563 60.96
v 188.72 60.23563 59.27999
v 188.64 60.23563 59.2
v 188.48 60.23563 60.96
>
>
>
>f 1/1/1 2/2/2 3/3/3
f 4/4/4 5/5/5 6/6/6
f 4/4/4 6/6/6 7/7/7
f 8/8/8 9/9/9 10/10/10
f 11/11/11 12/12/12 13/13/13
f 14/14/14 15/15/15 16/16/16
f 14/14/14 16/16/16 17/17/17
f 14/14/14 17/17/17 18/18/18
f 14/14/14 18/18/18 19/19/19
f 20/20/20 21/21/21 22/22/22
f 20/20/20 22/22/22 23/23/23
f 24/24/24 25/25/25 26/26/26
f 24/24/24 26/26/26 27/27/27
f 28/28/28 29/29/29 30/30/30
f 28/28/28 30/30/30 31/31/31
f 32/32/32 33/33/33 34/34/34
f 35/35/35 36/36/36 37/37/37
f 38/38/38 39/39/39 40/40/40
f 38/38/38 40/40/40 41/41/41
f 42/42/42 43/43/43 44/44/44
f 42/42/42 44/44/44 45/45/45
f 46/46/46 47/47/47 48/48/48
f 49/49/49 50/50/50 51/51/51
f 52/52/52 53/53/53 54/54/54
f 52/52/52 54/54/54 55/55/55
f 56/56/56 57/57/57 58/58/58
f 59/59/59 60/60/60 61/61/61
f 59/59/59 61/61/61 62/62/62
f 63/63/63 64/64/64 65/65/65

I am using the example below, but not working

```javascript
var recast = require("./recast.js-master/lib/recast.js");

recast.OBJLoader( 'teste.obj', function () {
    recast.build();
    recast.getRandomPoint(recast.cb(function(x, y, z){
      recast.findPath( 0, 0, 0,  x, y, z, 1000, recast.cb(function(route){ 
        console.log( "The shortest route contains", route.length, "corners" );
        console.log( "These corners are", route );
      }));
  }));
});
```

>error: NavMeshQuery is not ready

**Comment by vincent** [comment]
if you open it in Blender for example, does it render correctly ?

**Comment by rbatistajs** [comment]
is not rendering in blender  : /

I am using the following code to export the navmesh in Unity3D
```
static string MeshToString(Mesh mesh) {
		StringBuilder sb = new StringBuilder();
		
		sb.Append("g ").Append(mesh.name).Append("\n");
		foreach (Vector3 v in mesh.vertices) {
			sb.Append(string.Format("v {0} {1} {2}\n",v.x,v.y,v.z));
		}
		sb.Append("\n");
		foreach (Vector3 v in mesh.normals) {
			sb.Append(string.Format("vn {0} {1} {2}\n",v.x,v.y,v.z));
		}
		sb.Append("\n");
		foreach (Vector3 v in mesh.uv) {
			sb.Append(string.Format("vt {0} {1}\n",v.x,v.y));
		}
		for (int material = 0; material < mesh.subMeshCount; material++) {
			sb.Append("\n");
			//sb.Append("usemtl ").Append(mats[material].name).Append("\n");
			//sb.Append("usemap ").Append(mats[material].name).Append("\n");
			
			int[] triangles = mesh.GetTriangles(material);
			for (int i=0;i<triangles.Length;i+=3) {
				sb.Append(string.Format("f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n", triangles[i]+1, triangles[i+1]+1, triangles[i+2]+1));
			}
		}
		return sb.ToString();
	}
```
I am exporting the navmesh to work on the server side.

**Comment by vincent** [comment]
I'm sorry I don't know much about Unity, but it really seems there something wrong with the exporter.

Maybe try with an other one ?

**Comment by rbatistajs** [comment]
I'm just exporting the part in blue ...
![image](https://cloud.githubusercontent.com/assets/2729379/9385259/c6890fd8-472b-11e5-81dd-2b498def0ee5.png)

I can see now in the blender.
![image](https://cloud.githubusercontent.com/assets/2729379/9385356/6a892e92-472c-11e5-89e3-0173b9ba7a2d.png)

**Comment by vincent** [comment]
try this http://stackoverflow.com/a/20045654/1689894 or try to play with the UV maps settings.

I guess just exporting your mesh from Blender is not an option ?

**Comment by rbatistajs** [comment]
I used the example model, and created a nav mesh in unity, and now works perfectly.

![image](https://cloud.githubusercontent.com/assets/2729379/9392576/fc30c144-4753-11e5-981c-faae37b976f2.png)

![image](https://cloud.githubusercontent.com/assets/2729379/9392627/36a969c0-4754-11e5-9541-010452de053b.png)

**Comment by vincent** [comment]
I'm glad you figured it out.

I'll close this issue, feel free to comment if you have further questions.

Cheers
