### ISSUE TITLE
Not taking the shortest path

### ISSUE THREAD

**Issue by AmdEagle** [vincent/recast.js#19]
when using the recast.js given 2 points its doesnt return the shortest path it takes some weird long path to reach the destination
![capture](https://cloud.githubusercontent.com/assets/6722962/11551123/596349d6-99b1-11e5-9b6e-c0b2bb424000.PNG)

The pink dots are the start and location and green dots are the way points from recast.js. any idea why its taking this long winded path ?

**Comment by vincent** [comment]
Hi @BalakrishnanV sorry I haven't answer this for such a long time :/

Did you tried to test the same behaviour with the original Recast tool (with the same config obv.) ?

**Comment by vincent** [comment]
Closing; Feel free to reopen if needed.
